<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>JZ2440 Control</AssemblyName>
    <RootNamespace>Jz2440.Control</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jz2440.Control.Core\Jz2440.Control.Core.csproj" />
  </ItemGroup>
</Project>
